export const ActivityType = {
  BOARD_MEMBER_REMOVED : 'BOARD_MEMBER_REMOVED',
// Groups
  GROUP_CREATED : 'GROUP_CREATED',
  GROUP_UPDATED : 'GROUP_UPDATED',
  GROUP_DELETED : 'GROUP_DELETED',

  // Tasks
  TASK_CREATED : 'TASK_CREATED',
  TASK_UPDATED : 'TASK_UPDATED',
  TASK_DELETED : 'TASK_DELETED',
  TASK_MOVED : 'TASK_MOVED',

  // Task assignment
  TASK_ASSIGNED : 'TASK_ASSIGNED',
  TASK_UNASSIGNED : 'TASK_UNASSIGNED',

  // Task fields
  TASK_FIELD_CHANGED : 'TASK_FIELD_CHANGED',
  TASK_STATUS_CHANGED : 'TASK_STATUS_CHANGED',

  // Comments
  COMMENT_ADDED : 'COMMENT_ADDED',
  COMMENT_UPDATED : 'COMMENT_UPDATED',
  COMMENT_DELETED : 'COMMENT_DELETED',

  // Files
  FILE_UPLOADED : 'FILE_UPLOADED',
  FILE_DELETED : 'FILE_DELETED',

} as const
export type ActivityType = typeof ActivityType[keyof typeof ActivityType];