export const BoardPermission = {
  VIEW : "VIEW",

  EDIT : "EDIT",
  DELETE : "DELETE",

  CREATE_TASK : "CREATE_TASK",
  UPDATE_TASK : "UPDATE_TASK",
  DELETE_TASK : "DELETE_TASK",

  CREATE_GROUP : "CREATE_GROUP",
  UPDATE_GROUP : "UPDATE_GROUP",
  DELETE_GROUP : "DELETE_GROUP",

  CREATE_COLUMN : "CREATE_COLUMN",
  UPDATE_COLUMN : "UPDATE_COLUMN",
  DELETE_COLUMN : "DELETE_COLUMN",

  MANAGE_MEMBERS : "MANAGE_MEMBERS",
  MANAGE_SETTINGS : "MANAGE_SETTINGS",
  IMPORT_BOARD : "IMPORT_BOARD",
  EXPORT_BOARD : "EXPORT_BOARD",
} as const
export type BoardPermission = typeof BoardPermission[keyof typeof BoardPermission];
